const Formidable = require('formidable');
const fetch = require('node-fetch');
const FormData = require('form-data');
const fs = require('fs');

// Vercel/Netlify configuration to disable default body parsing, allowing Formidable to work.
export const config = {
  api: {
    bodyParser: false, 
  },
};

export default async (req, res) => {
  // Only allow POST requests
  if (req.method !== 'POST') {
    return res.status(405).send('Method Not Allowed');
  }

  // Get the Secret Webhook URL from Environment Variables (SECURE)
  const DISCORD_WEBHOOK_URL = process.env.DISCORD_WEBHOOK_URL;

  if (!DISCORD_WEBHOOK_URL) {
    return res.status(500).json({ success: false, message: 'Server Error: Webhook URL not configured.' });
  }

  // Initialize Formidable (Fixes "formidable is not a function")
  const form = new Formidable.IncomingForm();

  form.parse(req, async (err, fields, files) => {
    if (err) {
      console.error('Formidable Error:', err);
      return res.status(500).json({ success: false, message: 'Failed to parse form data.' });
    }

    // Re-package the incoming request into a new FormData for Discord
    const formDataToDiscord = new FormData();

    // 1. Append Text Fields
    // fields in formidable v3 are an object of arrays: { key: [value] }
    for (const key in fields) {
        // We take the first element in the array as the value
        formDataToDiscord.append(key, fields[key][0]);
    }

    // 2. Append File Data (Handles the uploaded file)
    const fileKey = Object.keys(files)[0]; 
    if (fileKey && files[fileKey][0]) {
        const file = files[fileKey][0];
        // Append file using a read stream for better memory efficiency
        formDataToDiscord.append('file', fs.createReadStream(file.filepath), {
            filename: file.originalFilename || 'uploaded_file',
            contentType: file.mimetype || 'application/octet-stream',
        });
    }

    // 3. Proxy the Request to Discord
    try {
      const discordResponse = await fetch(DISCORD_WEBHOOK_URL, {
        method: 'POST',
        body: formDataToDiscord,
        // MUST include headers generated by form-data
        headers: formDataToDiscord.getHeaders(), 
      });

      if (discordResponse.ok) {
        return res.status(200).json({ success: true, message: 'Report sent successfully.' });
      } else {
        const errorDetails = await discordResponse.text();
        console.error('Discord Proxy Error:', discordResponse.status, errorDetails);
        return res.status(discordResponse.status).json({ success: false, message: 'Failed to proxy request to Discord.', details: errorDetails });
      }
    } catch (fetchError) {
      console.error('Fetch Error:', fetchError);
      return res.status(500).json({ success: false, message: 'Network error during proxy attempt.' });
    }
  });
};
